name:                LDSC
version:             1.0.0
github:              "githubuser/LDSC"
license:             BSD3
author:              "Kai Zhang"
maintainer:          "kai@kzhang.org"
copyright:           "2021 Kai Zhang"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/LDSC#readme>

dependencies:
- base >= 4.7 && < 5
- async
- SafeSemaphore
- bioinformatics-toolkit
- bytestring
- conduit
- conduit-extra
- SciFlow
- text
- aeson
- binary
- mtl
- temporary
- shelly

library:
  source-dirs: src

executables:
  ldsc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    #- -rtsopts
    #- -with-rtsopts=-N
    dependencies:
    - LDSC
    - bioinformatics-toolkit
    - microlens-platform
    - conduit
    - SciFlow
    - SciFlow-app
    - SciFlow-remote
    - text
    - unordered-containers
    - data-default
    - yaml
